# Generated by Django 4.2.22 on 2025-07-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posthog", "0799_migrate_playlist_types_take_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalapikey",
            name="last_rotated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
