# Generated by Django 4.2.22 on 2025-07-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posthog", "0799_migrate_playlist_types_take_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledchange",
            name="failure_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="scheduledchange",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
